blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'blog.views.index', name="index"),
    url(r'^new/$', 'blog.views.new', name='new'),
    url(r'^(?P<pk>\d+)/$', 'blog.views.detail', name='detail'),
    url(r'^(?P<pk>\d+)/comments/new/$', 'blog.views.comment_new',
    name='comment_new'),
    url(r'^edit/(?P<pk>\d+)/$', 'blog.views.edit', name='edit'),
    url(r'^signup/joke/$', 'blog.views.signup_joke'),
    ]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', 'project.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^magazine/', include('megazine.urls', namespace='megazine')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^refresh/$', 'project.views.refresh', name='refresh'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

blog/models.py
from django.db import models
from django.core.files import File
from django.db.models.signals import pre_save
from blog.utils import random_name_upload_to, square_image, thumbnail


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to=random_name_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


def pre_on_post_save(sender, **kargs):
    post = kargs['instance']
    if post.image:
        max_width = 300
        if post.image.width > max_width or post.image.height > max_width:
            processed_file = thumbnail(post.image.file, max_width, max_width)
            post.image.save(post.image.name, File(processed_file))

pre_save.connect(pre_on_post_save, sender=Post)

class Comment(models.Model):
    post = models.ForeignKey(Post)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image')

    def clean_title(self):
        title = self.cleaned_data['title']
        if title:
            if len(title) < 10:
                raise forms.ValidationError("10글자 입력해라")
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class JokeSignupForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    age = forms.IntegerField(min_value=1)

    def clean_username(self):
        username = self.cleaned_data['username']
        if username:
            if username.startswith('이'):
                raise forms.ValidationError('저희 정책상, 이씨는 가입할 수 없어요. 죄송.')
            elif 'fuck' in username:
                raise forms.ValidationError('욕하지마세요!')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if email:
            if email.endswith('@nis.go.kr'):
                raise forms.ValidationError('국정원 이메일은 가입하실 수 없습니다.')
        return email

    def clean_age(self):
        age = self.cleaned_data['age']
        if age:
            if age < 19:
                raise forms.ValidationError('애들은 가라 !!!')
        return age

    def clean(self):
        username = self.cleaned_data.get('username', '')
        email = self.cleaned_data.get('email', '')
        age = self.cleaned_data.get('age', 1)

        print(repr(email))
        print(repr(age))

        if email.endswith('@seoul.go.kr') and age < 30:
            raise forms.ValidationError('20대 서울시청 공무원이 있을 수 있습니까?')
        return self.cleaned_data

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from blog.models import Post
from blog.forms import PostForm, CommentForm, JokeSignupForm
from django.contrib import messages


def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', {'post_list': post_list, })


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, "blog/post_detail.html", {'post': post,
         })


def comment_new(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, "새 댓글이 등록되었습니다.")
            return redirect('blog:detail', pk)
    else:
        form = CommentForm()
    return render(request, 'blog/form.html', {'form': form,})



def new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "새 글이 등록되었습니다.")
            return redirect('blog:index')
    else:
        form = PostForm()
    return render(request, 'blog/form.html', {'form': form,})


def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/form.html', {'form': form, })

def signup_joke(request):
    if request.method == 'POST':
        form = JokeSignupForm(request.POST)
        if form.is_valid():
            print('form.cleaned_data = {}'.format(form.cleaned_data))
            return redirect('blog.views.index')
    else:
        form = JokeSignupForm()
    return render(request, "blog/form.html", {
        'form': form,
    })

blog/templates/blog/form.html
{% load bootstrap3 %}

<!--
{% bootstrap_css %}
{% bootstrap_javascript %}
-->


<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css" />


<form action="" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "heart" %} Submit{% bootstrap_icon "star" %}
        </button>
    {% endbuttons %}
</form>

blog/templates/blog/index.html
{% extends "blog/layout.html" %}

{% block extra_head %}
<style>
#post_list .media {
    margin-bottom: 10px;
}
#post_list .media-object {
    width: 100px;
    height: 100px;
}
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" id="post_list">

        {% for post in post_list %}
            <div class="col-sm-6">
                <div class="media">
                    <div class="media-left">
                        <a href="/blog/{{ post.id }}/">
                            {% if post.image %}
                                <img class="media-object" src="{{ post.image.url }}" alt="{{ post.title }}" />
                            {% else %}
                                <img class="media-object" src="" alt="이미지없음" />
                            {% endif %}
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{{ post.title }}</h4>
                        {{ post.content|linebreaks }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

 <p class="text-center">
    <a href="{% url "blog:new" %}" class="btn btn-primary">새 포스팅</a>
</p>
{% endblock %}

blog/templates/blog/layout.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
<meta charset = "utf-8"/>
<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css" />
<title> student777님의 블로그 </title>
<head>
<style>
#footer {
    background-color: #333333;
    line-height: 20px;
    padding: 30px 20px;
    margin-top: 60px;
}
</style>
{% block extra_head %}
{% endblock %}
</head>
<body>

<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">LOL 대전기록</a>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 text-muted">
                파이썬 웹프레임워크인 <a href="http://djangoproject.com" target="_blank">Django</a> 로 만들었습니다.<br/>
            </div>
        </div>
    </div>
</footer>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        {{ post.title }}
                    </div>
                    <div class="panel-body">
                        {% if post.image %}
                            <p><img src="{{ post.image.url }}" /></p>
                        {% endif %}

                        {{ post.content|linebreaksbr }}
                    </div>
                </div>

                    <h4>댓글목록</h4>

                    <ul>
                    {% for comment in post.comment_set.all %}
                        <li>{{ comment.content }} at {{ comment.created_at }}</li>
                    {% empty %}
                        <li>등록된 댓글이 없습니다. </li>
                    {% endfor %}
                    </ul>

                    <hr/>
                    <p class="text-center">
                        <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-primary">새 댓글</a>
                        <a href="{% url "blog:index" %}" class="btn btn-primary">글 목록</a>
                        <a href="{% url "blog:edit" post.id %}" class="btn btn-primary">수정</a>
                        <a href="{% url "blog:index" %}" class="btn btn-primary">삭제</a>
                    </p>
            </div>
        </div>
    </div>
{% endblock %}