blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'blog.views.index', name="index"),
    url(r'^new/$', 'blog.views.new', name='new'),
    url(r'^(?P<pk>\d+)/$', 'blog.views.detail', name='detail'),
    url(r'^(?P<pk>\d+)/comments/new/$', 'blog.views.comment_new',
    name='comment_new'),
    url(r'^edit/(?P<pk>\d+)/$', 'blog.views.edit', name='edit'),
    url(r'^signup/joke/$', 'blog.views.signup_joke'),
    ]

megazine/urls.py
from django.conf.urls import url

urlpatterns =[
    url(r'^$', 'megazine.views.index', name='index'),
    url(r'^index_old/$', 'megazine.views.index_old', name='index_old'),
    url(r'^(?P<pk>\d+)/$', 'megazine.views.detail', name='detail'),
    url(r'^new/$', 'megazine.views.new', name='new'),
     url(r'^(?P<pk>\d+)/edit/$', 'megazine.views.edit', name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', 'megazine.views.delete', name='delete'),
    url(r'^(?P<pk>\d+)/comment_new/$', 'megazine.views.comment_new', name='comment_new'),
     url(r'^comment_edit/(?P<pk_comment>\d+)/$', 'megazine.views.comment_edit', name='comment_edit'),
    url(r'^comment_delete/(?P<pk_comment>\d+)/$', 'megazine.views.comment_delete', name='comment_delete'),
    url(r'^signup_old/$', 'megazine.views.signup_old', name='signup_old'),
    url(r'^test/$', 'megazine.views.test'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', 'project.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^magazine/', include('megazine.urls', namespace='megazine')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^refresh/$', 'project.views.refresh', name='refresh'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

megazine/models.py
from django.db import models
from megazine.utils import random_name_upload_to, thumbnail
from django.db.models.signals import pre_save
from django.core.files import File
from django.conf import settings


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to=random_name_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('Tag', blank=True)
    lnglat = models.CharField(max_length=50, blank=True, null=True, help_text='경도 위도 순으로 입력해주세요 ex)127, 35')

    def __str__(self):
        return self.title

    @property
    def lng(self):
        if self.lnglat:
            return self.lnglat.split(',')[0]

    @property
    def lat(self):
        if self.lnglat:
            return self.lnglat.split(',')[1]


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id) + self.content

    class Meta:
        ordering = ('-pk', )

def pre_on_post_save(sender, **kargs):
    post = kargs['instance']
    if post.image:
        max_width = 300
        if post.image.width > max_width or post.image.height > max_width:
            processed_file = thumbnail(post.image.file, max_width, max_width)
            post.image.save(post.image.name, File(processed_file))

pre_save.connect(pre_on_post_save, sender=Post)

megazine/forms.py
from django import forms
from megazine.models import Post, Comment
import re
from project.widgets import PointWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image', 'tags', 'lnglat')
        widgets = {
            'lnglat': PointWidget,
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if title:
            if len(title) < 3:
                raise forms.ValidationError("3글자 이상 입력해라")
        return title

    def clean_lnglat(self):
        lnglat = self.cleaned_data.get('lnglat', '')
        if lnglat:
            if not re.match(r'\d+\.?\d*,\d+\.?\d*', lnglat):
                raise forms.ValidationError('invalid lnglat')
        return lnglat


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )


class SignupForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    age = forms.IntegerField(min_value=1)

    def clean_username(self):
        username = self.cleaned_data['username']
        if username:
            if username.startswith('kim'):
                raise forms.ValidationError('김정은이')
            elif 'fuck' in username:
                raise forms.ValidationError('욕하지마세요')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if email:
            if email.endswith('@naver.com'):
                raise forms.ValidationError('야레야레')
        return email

    def clean_age(self):
        age = self.cleaned_data['age']
        if age:
            if age < 19:
                raise forms.ValidationError('애들은 가라 !!!')
        return age

    def clean(self):
        username = self.cleaned_data.get('username', '')
        email = self.cleaned_data.get('email', '')
        age = self.cleaned_data.get('age', 1)
        return self.cleaned_data

megazine/views.py
from django.shortcuts import render, get_object_or_404, redirect
from megazine.models import Post, Comment
from megazine.forms import PostForm, CommentForm, SignupForm
from django.core.paginator import InvalidPage, Paginator
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User


def index(request):
    page_number = int(request.GET.get('page', 1))
    if request.GET.get('tags'):
        tag = request.GET.get('tags')
        post_list = Post.objects.filter(tags__name__startswith=tag)
    else:
        post_list = Post.objects.all()
    paginate_by = 12

    paginator = Paginator(post_list, paginate_by)
    try:
        page = paginator.page(page_number)
    except InvalidPage:
        raise Http404('invalid page {}'.format(page_number))
    return render(request, "megazine/index.html", {
        'post_list': page.object_list,
        'page': page,
    })


def index_old(request):
    post_list = Post.objects.all()
    return render(request, 'megazine/index_old.html', {'post_list':
                  post_list, })


def detail(request, pk):
    if request.is_ajax():
        return HttpResponse({'jquery': 'ok'})
    else:
        post = get_object_or_404(Post, pk=pk)
        comment_form = CommentForm(auto_id=False)
        return render(request,
                      "megazine/detail.html",
                      {'post': post, 'comment_form': comment_form, })


@staff_member_required
def new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "새 글이 등록되었습니다")
            return redirect('megazine:index')
    else:
        form = PostForm()
    return render(request, 'megazine/form.html', {
        'form': form, 'title': 'New Post'})


@staff_member_required
def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "글 수정에 성공하였습니다")
            return redirect('megazine:index')
    else:
        form = PostForm(instance=post)
    return render(request, 'megazine/form.html', {
        'form': form, 'title': 'Edit Post'})


@staff_member_required
def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        messages.success(request, "글이 삭제되었습니다")
        return redirect('megazine:index')
    return render(request, 'megazine/post_delete_confirm.html', {'post': post})


def comment_new(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            if request.is_ajax():
                comment = form.save(commit=False)
                comment.post = post
                if request.user.is_authenticated():
                    comment.author = request.user
                else:
                    comment.author = User.objects.get(username='veil')
                comment.save()
                return render(request, 'megazine/comment_row.html', {
                    'comment': comment,
                })
    return redirect('megazine:detail', pk)


@login_required
def comment_edit(request, pk_comment):
    comment = get_object_or_404(Comment, pk=pk_comment)
    if request.user.id == comment.author_id:
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                    form.save()
                    messages.success(request, '댓글을 수정했습니다.')
                    return redirect('megazine:detail', comment.post.pk,)
        else:
            form = CommentForm(instance=comment)
        return render(request, 'form.html', {
            'form': form,
            'post': comment.post,
            'title': 'Edit comment'
        })
    else:
        messages.warning(request, '댓글수정은 작성자만 가능합니다')
        return redirect('megazine:detail', comment.post_id)


@login_required
def comment_delete(request, pk_comment):
    comment = get_object_or_404(Comment, pk=pk_comment)
    if request.user.id == comment.author_id:
        if request.method == 'POST':
            comment.delete()
            return HttpResponse({'jquery': 'ok'})  # ?? TODO
        else:
            return redirect('megazine:index')
    else:
        messages.warning(request, '댓글수정은 작성자만 가능합니다')
        return redirect('megazine:detail', comment.post_id)


def signup_old(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            print('가입 승인')
            print('form.cleaned_data = {}'.format(form.cleaned_data))
            messages.success(request, '회원가입 신청 완료')
            return redirect('megazine:index')
        else:
            print("가입 거절")
    else:
        form = SignupForm()
    return render(request, "form.html", {'form': form, })


def test(request):
    messages.debug(request, 'hello debug')
    messages.info(request, 'hello info')
    messages.success(request, 'hello success')
    messages.warning(request, 'hello waring')
    messages.error(request, 'hello error')
    return render(request, "megazine/test.html", {})

megazine/templates/megazine/comment_row.html
<tr>
  <td>
    {% if forloop.counter %}
      <span style="display:inline-block">{{ forloop.counter }}</span>
   {% else %}
      <span style="color:red; font-family:bold">new</span>
   {% endif %}
  </td>
  <td>{{ comment.author }}</td>
  <td>{{ comment.content }}</td>
  <td>
      <a href="{% url "megazine:comment_edit" comment.pk %}"><span class="icon glyphicon glyphicon-edit" aria-hidden="true"></span></a>
      <a href="{% url "megazine:comment_delete" comment.pk %}"data-comment-id="comment_{{ comment.pk }}" id="delete_comment">&nbsp;<span class="icon glyphicon glyphicon-remove" aria-hidden="true"></span></a>
  </td>
  <td>{{ comment.created_at|date:"y.m.d H:i:s" }}</td>
</tr>

megazine/templates/megazine/comment_row_old.html
<!--detail.html
<div class="panel panel-default" >
  <div class="panel-heading">댓글 목록</div>
    <ul class="list-group" id="comment_list">
        {% for comment  in post.comment_set.all %}
        {% include "megazine/comment_row.html" %}
        {% empty %}
            <li class="list-group-item">등록된 댓글이 없습니다. </li>
        {% endfor %}
    </ul>
</div>
-->

<li id="comment_{{ comment.pk }}" class="list-group-item " >
    {% if forloop.counter %}
    <span style="display:inline-block">{{ forloop.counter }}.</span>
    {% else %}
    <span style="color:red; font-family:bold">new</span>
    {% endif %}
    <span>{{ comment.author }} |</span>
    <div style="display:inline-block">&nbsp;{{ comment.content }}</div>
    <a href="{% url "megazine:comment_edit" comment.pk %}"><span class="icon glyphicon glyphicon-edit" aria-hidden="true"></span></a>
    <a href="{% url "megazine:comment_delete" comment.pk %}"data-comment-id="comment_{{ comment.pk }}" id="delete_comment">&nbsp;<span class="icon glyphicon glyphicon-remove" aria-hidden="true"></span></a>
    <div style="float:right" class="date">&nbsp; {{ comment.created_at|date:"y.m.d H:i:s" }}</div>
</li>

megazine/templates/megazine/detail.html
{% extends "megazine/layout.html" %}

{% block extra_head%}
<style>
    .icon{
        color: black;
        font-size:10px;
    }
    .date{
        font-size: 12px;
    }
    .form-group{
        width:100%;
        margin-bottom: 10px;
    }
    #addComment{
        width: 30%;
        margin-bottom:10px;
    }
    div>div>div>div>a{
        width: 16%;
    }
</style>
<script>
    $(function(){
        var tex = $("textarea:first");
        tex.className = "form-control";
        tex.attr("rows", "3");
        tex.css("width", "100%");
        $("form div").contents().filter(function(){ return this.nodeType != 1; }).remove();
    });
    $(function(){
        $("#comment_form").submit(function() {
            var url = $(this).attr("action");
            var content_value = $(this).find("textarea[name=content]").val();
            if(content_value ==""){
                $.toaster({
                        title: 'fail',
                        priority: 'danger',
                        message: '내용을 입력해 주세요'
                    });
                return false;
            }
            $.ajax({
                url: url,
                method: "POST",
                data: {
                    content: content_value
                }
            }).fail(function() {
                $.toaster({
                        title: 'fail',
                        priority: 'danger',
                        message: '다시 시도해 주세요'
                });
            }).done(function(html) {
                $("#comment_list").prepend(html);
                $.toaster({
                        title: 'success',
                        priority: 'success',
                        message: '새 댓글이 등록되었습니다'
                });
                $("textarea")[0].value="";
            });
            return false;
        });
        $(document).on('click', '#delete_comment', function(){
            if ( confirm("Are you sure?") ) {
                var url = $(this).attr("href");
                var comment_id = $(this).data("comment-id");
                $.ajax({
                    url: url,
                    method: "POST"
                }).fail(function() {
                    $.toaster({
                        title: 'fail',
                        priority: 'danger',
                        message: '다시 시도해 주세요'
                    });
                }).done(function() {
                    $("#" + comment_id).remove();
                    $.toaster({
                        title: 'success',
                        priority: 'success',
                        message: '댓글을 삭제하였습니다'
                    });
                });
            }
            return false;
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading" style="font-size:20px;">
                    {{ post.title|safe }}
                </div>
                 <div class="panel-heading" style="padding:5px 10px 5px 10px">
                    <span>Writer: {{ post.author}}&nbsp;</span>
                    <span>Clicks:&nbsp;{{ post.author}}&nbsp;</span>
                    <span style="float:right"class="date">{{ post.created_at|date:"y.m.d H:i:s" }}</span>
                </div>
                <div class="panel-body">
                    {% if post.image %}
                        <p><img src="{{ post.image.url }}" /></p>
                    {% else %}
                        <p><img src="http://lorempixel.com/300/300/cats/{{ post.id | get_digit:"1"}}"/></p>
                    {% endif %}

                    {{ post.content|linebreaksbr }}
                </div>
                <div class="panel-body">
                    {% if post.lnglat %}
                        <a id="fold">show map</a>
                        <p><div id="map"></div></p>
                            <script>
                            $("#fold").click(function() {
                                $("#map").show();
                                var lat = {{ post.lat }};
                                var lng = {{ post.lng }};
                                var position = {lat: lat, lng: lng};
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    center: position,
                                    zoom: 8
                                });
                                var marker = new google.maps.Marker({
                                    position: position,
                                    map: map
                                });
                                $("#map").css("height", "300px")
                            });
                            </script>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    <span>Tags:</span>
                    {% for tag in post.tags.all %}
                        <span>#{{tag}}&nbsp;</span>
                    {% endfor %}
                </div>

            </div>


            <div class="text-center panel">
                <a href="{% url "megazine:index" %}" class="btn btn-default"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp;list</a>
                <a href="{% url "megazine:edit" post.id %}" class="btn btn-default"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;edit</a>
                <a href="{% url "megazine:delete" post.id %}" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;delete</a>
                <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">&nbsp;{{ post.author_id }}</span></a>
                <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true">&nbsp;{{ post.author_id }}</span></a>
            </div>

             <div class="panel">
            <form id="comment_form" class = "form-inline" action="{% url "megazine:comment_new" post.pk %}" method="POST">
                <div class="form-group text-center">
                {% csrf_token %}
                    {{ comment_form }}
                <input id="addComment" style="float:right" type="submit" value="add a comment" class="btn btn-default" />
                </div>
            </form>
            </div>

            <div class="panel panel-default">
              <div class="panel-heading ">comment list</div>
                  <table class="table" id="comment_list">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>author</th>
                        <th>contents</th>
                        <th>edit/remove</th>
                        <th>date</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for comment  in post.comment_set.all %}
                            {% include "megazine/comment_row.html" %}
                        {% empty %}
                            <tr><td>등록된 댓글이 없습니다.</td></tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
                <hr/>
            </div>
        </div>
    </div>
{% endblock %}

megazine/templates/megazine/index_old.html
{% extends "megazine/layout.html" %}
{% load thumbnail %}
{% block extra_head %}
<style>
    #post_list .media {
        margin-bottom: 10px;
    }
    #post_list .media-object {
        width: 100px;
        height: 100px;
    }
    div.media-body{
        max-height:100px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" id="post_list">
        {% for post in post_list %}
            <div class="col-sm-6">
                <div class="media">
                    <div class="media-left">
                        <a href="/megazine/{{ post.id }}/">
                            {% if post.image %}
                                {% thumbnail post.image "100x100" crop='center' quality=80 as im %}
                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height}}">
                                {% endthumbnail %}
                            {% else %}
                                <img src="http://lorempixel.com/100/100/cats/{{ post.id | get_digit:"1"}}"/>
                            {% endif %}
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><strong>{{ post.title }}</strong></h4>
                        {{ post.content|linebreaks|truncatechars:55 }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<p class="text-center">
    <a href="{% url "megazine:new" %}" class="btn btn-info">새 포스팅</a>
</p>
{% endblock %}

megazine/templates/megazine/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html"; charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Project/magazine</title>
  <link rel="icon" href="{% static 'icon.jpg' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css' %}" />
  <link type="text/css" href="{% static 'layout.css' %}" rel="stylesheet">
  <style>
    #footer {
        line-height: 20px;
        padding: 30px 20px;
        background-color:#F8F8F8;
    }
    *{
        font-family: "나눔고딕";
    }
    html, body{
      height:100%;
    }
  </style>
  <script src="{% static "jquery-1.11.3.min.js" %}"></script>
  <script src="{% static "bootstrap-3.3.5-dist/js/bootstrap.min.js" %}"></script>
  <script src="{% static "jquery.toaster.js" %}"></script>
  <script src="{% static "jquery.csrf.js" %}"></script>
  <script src="//maps.googleapis.com/maps/api/js"></script>
  {% block extra_head %}
  {% endblock %}
</head>

<body role="document">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "megazine:index" %}" id="dd">Magazine</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url "megazine:index" %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a></li>
        <li><a href="#about"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> About</a></li>
        <li><a href="#contact"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> Contact</a></li>
        <li><a href="#visitor"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Visitor</a></li>
        <li>
          <form action="/magazine/" class="navbar-form navbar-right" method="GET">
              <div class="form-group">
                <input type="text" placeholder="ex)statistics" class="form-control" name="tags">
                <button type="submit" class="btn btn-default">search</button>
              </div>
          </form>
        </li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url "megazine:new" %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> New Post</a></li>
        <li class="dropdown">
          {% if not user.is_authenticated %}
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="" onclick="window.open('{% url "signup" %}', 'newwindow', 'width=500, height=580'); return false;">Signup</a></li>
            <li><a href="" onclick="window.open('{% url "login" %}?next=/refresh', 'newwindow', 'width=500, height=450'); return false;">Login by ID/PW</a></li>
            <li><a href="" onclick="window.open('{% url "login_email" %}', 'newwindow', 'width=500, height=280'); return false;">Login by Email</a></li>
          {% else %}
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user }}<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url "info" %}">Your account</a></li>
              <li><a href="{% url "logout" %}?next=/magazine">Logout</a></li>
            </ul>
          {% endif %}
        </li>
      </ul>


    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
      <div class="col-sm-12">
          {% if messages %}
              {% for message in messages %}
              <script>
                  $.toaster({
                      title: '{{ message.tags }}',
                      priority: '{{ message.tags }}',
                      message: '{{ message }}'
                  });
              </script>
              {% endfor %}
          {% endif %}
      </div>
  </div>
</div>

{% block content %}
{% endblock %}
<hr>


<footer class="footer">
  <div class="container">
    <div class="row">
        <div class="col-sm-6 text-muted">
            파이썬 웹프레임워크인 <a href="http://djangoproject.com" target="_blank">Django</a> 로 만들었습니다.<br/>
        </div>
        <div class="col-sm-6 text-right">
            <a href="naver.com" target="_blank">Kim awet</a>
        </div>
    </div>
  </div>
</footer>
</body>
</html>

megazine/templates/megazine/layout_old.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <title> MEGAAAAAAAAZINE</title>
    <meta charset = 'utf-8'/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css' %}" />
    <style>
        #dd{
            font-family: "sans-serif" bold;
            font-size: 26px;
            width: 50vw;
        }
        #footer {
            background-color: #f8f8f8;
            line-height: 20px;
            padding: 20px 20px 300px 20px;
        }
        *{
            font-family: "나눔고딕";
        }
        .navbar {
            border-radius: 0;
        }
        img {
            max-width: 100%;
        }
    </style>
    <script src="{% static "jquery-1.11.3.min.js" %}"></script>
    <script src="{% static "bootstrap-3.3.5-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "jquery.toaster.js" %}"></script>
    <script src="{% static "jquery.csrf.js" %}"></script>
    {% block extra_head%}
    {% endblock %}
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "megazine:index" %}" id="dd"><strong style="color:red;">BREAKING</strong> news</a>
            </div>
            <div id="navbar-top" class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url "megazine:new" %}">새 포스팅</a></li>
                    {% if not user.is_authenticated %}
                    <li><a href="" onclick="window.open('{% url "signup" %}?next={{ request.path }}', 'newwindow', 'width=500, height=500'); return false;">Signup</a></li>
                    <li><a href="{% url "login" %}?next={{ request.path }}">Login by ID</a></li>
                    <li><a href="{% url "login_email" %}">Login by Email</a></li>
                    {% else %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "logout" %}?next={{ request.path }}">로그아웃</a></li>
                        </ul>
                    </li>
                {% endif %}
                </ul>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% if messages %}
                    {% for message in messages %}
                    <script>
                        $.toaster({
                            title: '{{ message.tags }}',
                            priority: '{{ message.tags }}',
                            message: '{{ message }}'
                        });
                    </script>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
    <footer id="footer">
        <div class="container">
            <p>
                파이썬 웹프레임워크인 <a href="http://djangoproject.com" target="_blank">Django</a> 로 만들었습니다.<br/>
            </p>
        </div>
    </footer>
</body>
</html>